# TMForum Proxy Configuration Example
# Copy this file and modify as needed

# Remote server configuration
base_url: "https://tmf.dome-marketplace-sbx.org"
timeout: 30  # seconds

# Object types to retrieve and validate
object_types:
  - "productOffering"
  - "productSpecification"
  - "productOfferingPrice"
  - "category"
  - "individual"
  - "organization"
  - "productCatalog"
  - "customer"
  - "product"
  - "service"

# Pagination settings
pagination_enabled: true
page_size: 100
max_objects: 10000

# Validation settings
validate_required_fields: true
validate_related_party: true

# Output settings
output_dir: "./reports"
report_file: "tmf_validation_report.md"
