package service

import (
	"testing"
)

const testAccessToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItckxwSkhNVkhCSUQ0Q2FRX0dsTjhFTEprQ0tYMUJWUzhMTzd6enU1cTFVIn0.eyJleHAiOjE3NjkwODk4NzMsImlhdCI6MTc2NjQ5Nzg3MywiYXV0aF90aW1lIjoxNzY2NDk3ODczLCJqdGkiOiJvbnJ0YWM6MTNkNTVjOTMtNjQyZC1jNjBhLTk5OTAtZjA5NDFiMzBlZDFiIiwiaXNzIjoiaHR0cHM6Ly9pZHAuZGV2LmNsb3VkLXcuZW52cy5yZWRpc2JlLmNvbS9hdXRoL3JlYWxtcy9kZXYtaXNiZSIsImF1ZCI6WyJpc2JlLXBvcnRhbC1kZXYiLCJhY2NvdW50Il0sInN1YiI6ImIyMzQ5ZTMxLWEyOTktNGU5Yi04ZGQxLWQxMWExZDFmNzBjMSIsInR5cCI6IkJlYXJlciIsImF6cCI6Imh0dHBzOi8vY2F0YWxvZy5pc2Jlb25ib2FyZC5jb20iLCJzaWQiOiI3MzQ1MzY0NS1mZmNmLTY3ZTAtYmE1Mi1lMWJmYWY4MTgxZTAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vY2F0YWxvZy5kZXYuY2xvdWQtdy5lbnZzLnJlZGlzYmUuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWRldi1pc2JlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9yZ2FuaXphdGlvbiBlbWFpbCBwcm9maWxlIiwidXNlcl9pZGVudGlmaWVyIjoiMTIzNDU2NzhBIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm9yZ2FuaXphdGlvbiI6IkFMQVNUUklBIiwibmFtZSI6IkpvaG4gRG9lIiwib3JnYW5pemF0aW9uX2lkZW50aWZpZXIiOiJWQVRFUy1HODc5MzYxNTkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqZXN1c0BhbGFzdHJpYS5pbyIsInBvd2VyIjpbeyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJNYW5hZ2VtZW50IiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiSGVscGRlc2siLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJCYWFTIiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiRmF1Y2V0IiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiUmdwZCIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik5vdGlmaWNhdGlvbnMiLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiKiJdLCJkb21haW4iOiJJU0JFIiwiZnVuY3Rpb24iOiJTYyIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IldpemFyZCIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik5vdGFyaXphdGlvbiIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IlRva2VuaXphdGlvbiIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyIqIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IklkZW50aXR5IiwidHlwZSI6Im9yZ2FuaXphdGlvbiJ9LHsiYWN0aW9uIjpbIioiXSwiZG9tYWluIjoiSVNCRSIsImZ1bmN0aW9uIjoiRW5yb2xsbWVudCIsInR5cGUiOiJvcmdhbml6YXRpb24ifSx7ImFjdGlvbiI6WyJFeGVjdXRlIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6Ik9uYm9hcmRpbmciLCJ0eXBlIjoib3JnYW5pemF0aW9uIn0seyJhY3Rpb24iOlsiQ3JlYXRlIiwiVXBkYXRlIiwiRGVsZXRlIl0sImRvbWFpbiI6IklTQkUiLCJmdW5jdGlvbiI6IlByb2R1Y3RPZmZlcmluZyIsInR5cGUiOiJvcmdhbml6YXRpb24ifV0sImdpdmVuX25hbWUiOiJKb2huIiwidXNlciI6IkpvaG4gRG9lIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJlbWFpbCI6Implc3VzQGFsYXN0cmlhLmlvIn0.Nh9qvh22i9IaM1V_oV70XwQHnlnv0QELQb2Jjm1UZUtyv8VH2npC77JV0wM88EuzTunFBoybbqy30LCygkxB7TEPVyb7oCZ4uLvli2eA4gAF8gVHUkz7RAIohKSijUJrMhQOFsTc8Mfk1VEviqAJ-P4khj5ZIcnvOvpCxIaA8m5rJ7ktAMMwLd5zj1eab1tbU628sXwI66RbPTcI_FeEX_-6Qex662G76iKX2wCnDktAldlLAuk5869Ue0nWuNv3quA0sTWJFVEjcQvNfX5dB9Ny7I4bgMwFidqQLIiyDzEzOwBB5c27ATT9QIu8nYwLi_J60o74olXxv51PsauXjA"

func TestProcessAccessToken(t *testing.T) {
	s := newTestService(t)

	t.Run("UsingTestAccessToken", func(t *testing.T) {
		// testAccessToken is defined in callerinfo.go
		claims, user, err := s.ProcessAccessToken(testAccessToken)

		// The current implementation of ProcessAccessToken expects a 'vc' claim.
		// The testAccessToken provided does not have it, so it returns an error.
		// We assert this behavior for now.
		if err != nil {
			t.Logf("ProcessAccessToken returned error as expected: %v", err)
			if err.Error() != "missing 'vc' in JWT claims" {
				t.Errorf("Expected error 'missing vc in JWT claims', got: %v", err)
			}
			return
		}

		// If the implementation is updated to support the token format, these assertions will run.
		if claims == nil {
			t.Error("Expected claims to be returned")
		}
		if user == nil {
			t.Fatal("Expected user to be returned")
		}

		// Verify fields from the token payload
		// "organization_identifier": "VATES-G87936159"
		if user.OrganizationIdentifier != "VATES-G87936159" {
			t.Errorf("Expected OrganizationIdentifier 'VATES-G87936159', got '%s'", user.OrganizationIdentifier)
		}
		// "email": "jesus@alastria.io"
		if user.EmailAddress != "jesus@alastria.io" {
			t.Errorf("Expected EmailAddress 'jesus@alastria.io', got '%s'", user.EmailAddress)
		}
		if !user.IsAuthenticated {
			t.Error("Expected IsAuthenticated to be true")
		}
	})
}
